const LANG = {
  vi: {
    home: 'Trang chủ',
    about: 'Giới thiệu',
    setting: 'Cài đặt',
    todoTitle: (name) => name ? `Danh sách cần làm của ${name}` : 'Danh sách cần làm',
    addPlaceholder: 'Thêm công việc cần làm',
    addButton: 'Thêm',
    usernameModalTitle: 'Nhập tên của bạn',
    usernameModalPlaceholder: 'Tên của bạn...',
    usernameModalSave: 'Lưu',
    settingTitle: 'Cài đặt',
    changeName: 'Đổi tên người dùng',
    editName: 'Sửa',
    darkMode: 'Chế độ tối',
    darkOn: 'Bật',
    darkOff: 'Tắt',
    language: 'Ngôn ngữ',
    vi: 'Tiếng Việt',
    en: 'English',
    warning: 'Lưu ý: Nếu xóa dữ liệu hoặc xóa bộ nhớ đệm trình duyệt, toàn bộ dữ liệu sẽ bị mất vĩnh viễn.',
    reinput: 'Nhập lại tên',
  },
  en: {
    home: 'Home',
    about: 'About Us',
    setting: 'Setting',
    todoTitle: (name) => name ? `Todo list of ${name}` : 'Todo list',
    addPlaceholder: 'Add a todo',
    addButton: 'Add',
    usernameModalTitle: 'Enter your name',
    usernameModalPlaceholder: 'Your name...',
    usernameModalSave: 'Save',
    settingTitle: 'Setting',
    changeName: 'Change username',
    editName: 'Edit',
    darkMode: 'Dark mode',
    darkOn: 'On',
    darkOff: 'Off',
    language: 'Language',
    vi: 'Vietnamese',
    en: 'English',
    warning: 'Warning: If you clear data or browser cache, all data will be lost permanently.',
    reinput: 'Re-enter name',
  }
};

export default LANG; 